// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID int    `json:"userId"`
}
