// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/carlosvallim/gologin/models"
)

type NewTodo struct {
	Text   string `json:"text"`
	UserID int    `json:"userId"`
}

type Todo struct {
	ID      string          `json:"id"`
	Text    string          `json:"text"`
	Done    bool            `json:"done"`
	Usuario *models.Usuario `json:"usuario"`
}
